use crate::audit;
use crate::config::{AppConfig, DeviceRule, EnforcementMode};
use anyhow::{Context, Result};
use std::fs;
use std::path::PathBuf;
use std::process::Command;
use tracing::warn;

#[derive(Default)]
pub struct EnforcementResult {
    pub rollback_commands: Vec<String>,
    pub notes: Vec<String>,
}

pub struct EnforcementOrchestrator;

impl EnforcementOrchestrator {
    pub fn apply(cfg: &AppConfig) -> Result<EnforcementResult> {
        match cfg.enforcement.mode {
            EnforcementMode::GatewayOnly => Ok(EnforcementResult::default()),
            EnforcementMode::DhcpAssist => apply_dhcp_assist(cfg),
            EnforcementMode::PolicyRoute => apply_policy_route(cfg),
        }
    }
}

fn selected_targets(cfg: &AppConfig) -> Vec<DeviceRule> {
    if cfg.device_policy.allowlist.is_empty() {
        return vec![];
    }
    if cfg.enforcement.targets.is_empty() {
        return cfg.device_policy.allowlist.clone();
    }
    cfg.device_policy
        .allowlist
        .iter()
        .filter(|d| cfg.enforcement.targets.iter().any(|t| t == &d.name))
        .cloned()
        .collect()
}

fn apply_dhcp_assist(cfg: &AppConfig) -> Result<EnforcementResult> {
    let mut out = EnforcementResult::default();
    let targets = selected_targets(cfg);
    let gateway_ip = detect_primary_ipv4().unwrap_or_else(|_| "192.168.1.2".to_string());
    let dhcp_file = cfg.runtime.work_dir.join("dhcp-assist.dnsmasq.conf");

    let mut body = String::new();
    body.push_str("# generated by ok-proxy\n");
    body.push_str(&format!("dhcp-option=option:router,{}\n", gateway_ip));
    body.push_str(&format!("dhcp-option=option:dns-server,{}\n", gateway_ip));
    for t in targets {
        if let Some(mac) = t.mac {
            body.push_str(&format!("dhcp-host={},{}\n", mac, t.ip));
        }
    }
    fs::create_dir_all(&cfg.runtime.work_dir)
        .with_context(|| format!("failed to create {}", cfg.runtime.work_dir.display()))?;
    fs::write(&dhcp_file, body)
        .with_context(|| format!("failed to write {}", dhcp_file.display()))?;
    out.notes.push(format!(
        "dhcp-assist config generated: {}",
        dhcp_file.display()
    ));
    audit::log(
        cfg,
        "dhcp_assist_generated",
        &format!("file={}", dhcp_file.display()),
    )?;

    #[cfg(target_os = "linux")]
    {
        // Optional automatic deployment for dnsmasq in authorized networks.
        if cfg.security.allow_unsafe_experimental {
            let target = "/etc/dnsmasq.d/ok-proxy.conf";
            run("cp", &[dhcp_file.display().to_string(), target.to_string()])?;
            run("systemctl", &["restart".to_string(), "dnsmasq".to_string()])?;
            out.rollback_commands.push(format!("rm -f {}", target));
            out.rollback_commands
                .push("systemctl restart dnsmasq".to_string());
            audit::log(cfg, "dhcp_assist_deployed", "deployed to /etc/dnsmasq.d")?;
        }
    }

    Ok(out)
}

fn apply_policy_route(cfg: &AppConfig) -> Result<EnforcementResult> {
    let mut out = EnforcementResult::default();
    let targets = selected_targets(cfg);
    if targets.is_empty() {
        warn!("policy-route mode has no selected targets");
        return Ok(out);
    }

    #[cfg(target_os = "linux")]
    {
        for target in targets {
            add_tcp_redirect_for_ip(cfg, &target.ip, &mut out)?;
            add_dns_redirect_for_ip(cfg, &target.ip, &mut out)?;
            if let Some(mac) = target.mac {
                add_tcp_redirect_for_mac(cfg, &mac, &mut out)?;
                add_dns_redirect_for_mac(cfg, &mac, &mut out)?;
            }
        }
        audit::log(
            cfg,
            "policy_route_applied",
            &format!("targets={}", cfg.enforcement.targets.join(",")),
        )?;
    }

    #[cfg(not(target_os = "linux"))]
    {
        out.notes.push(
            "policy-route auto-apply is currently implemented on linux; skipped on this platform"
                .to_string(),
        );
    }

    Ok(out)
}

#[cfg(target_os = "linux")]
fn add_tcp_redirect_for_ip(cfg: &AppConfig, ip: &str, out: &mut EnforcementResult) -> Result<()> {
    let check_args = vec![
        "-t".to_string(),
        "nat".to_string(),
        "-C".to_string(),
        "PREROUTING".to_string(),
        "-s".to_string(),
        ip.to_string(),
        "-p".to_string(),
        "tcp".to_string(),
        "-j".to_string(),
        "REDIRECT".to_string(),
        "--to-ports".to_string(),
        cfg.inbound.redir_port.to_string(),
    ];
    let add_args = vec![
        "-t".to_string(),
        "nat".to_string(),
        "-A".to_string(),
        "PREROUTING".to_string(),
        "-s".to_string(),
        ip.to_string(),
        "-p".to_string(),
        "tcp".to_string(),
        "-j".to_string(),
        "REDIRECT".to_string(),
        "--to-ports".to_string(),
        cfg.inbound.redir_port.to_string(),
    ];
    maybe_add_iptables_rule("iptables", &check_args, &add_args, out)
}

#[cfg(target_os = "linux")]
fn add_dns_redirect_for_ip(cfg: &AppConfig, ip: &str, out: &mut EnforcementResult) -> Result<()> {
    for proto in ["udp", "tcp"] {
        let check_args = vec![
            "-t".to_string(),
            "nat".to_string(),
            "-C".to_string(),
            "PREROUTING".to_string(),
            "-s".to_string(),
            ip.to_string(),
            "-p".to_string(),
            proto.to_string(),
            "--dport".to_string(),
            "53".to_string(),
            "-j".to_string(),
            "REDIRECT".to_string(),
            "--to-ports".to_string(),
            cfg.inbound.dns_port.to_string(),
        ];
        let add_args = vec![
            "-t".to_string(),
            "nat".to_string(),
            "-A".to_string(),
            "PREROUTING".to_string(),
            "-s".to_string(),
            ip.to_string(),
            "-p".to_string(),
            proto.to_string(),
            "--dport".to_string(),
            "53".to_string(),
            "-j".to_string(),
            "REDIRECT".to_string(),
            "--to-ports".to_string(),
            cfg.inbound.dns_port.to_string(),
        ];
        maybe_add_iptables_rule("iptables", &check_args, &add_args, out)?;
    }
    Ok(())
}

#[cfg(target_os = "linux")]
fn add_tcp_redirect_for_mac(cfg: &AppConfig, mac: &str, out: &mut EnforcementResult) -> Result<()> {
    let check_args = vec![
        "-t".to_string(),
        "nat".to_string(),
        "-C".to_string(),
        "PREROUTING".to_string(),
        "-m".to_string(),
        "mac".to_string(),
        "--mac-source".to_string(),
        mac.to_string(),
        "-p".to_string(),
        "tcp".to_string(),
        "-j".to_string(),
        "REDIRECT".to_string(),
        "--to-ports".to_string(),
        cfg.inbound.redir_port.to_string(),
    ];
    let add_args = vec![
        "-t".to_string(),
        "nat".to_string(),
        "-A".to_string(),
        "PREROUTING".to_string(),
        "-m".to_string(),
        "mac".to_string(),
        "--mac-source".to_string(),
        mac.to_string(),
        "-p".to_string(),
        "tcp".to_string(),
        "-j".to_string(),
        "REDIRECT".to_string(),
        "--to-ports".to_string(),
        cfg.inbound.redir_port.to_string(),
    ];
    maybe_add_iptables_rule("iptables", &check_args, &add_args, out)
}

#[cfg(target_os = "linux")]
fn add_dns_redirect_for_mac(cfg: &AppConfig, mac: &str, out: &mut EnforcementResult) -> Result<()> {
    for proto in ["udp", "tcp"] {
        let check_args = vec![
            "-t".to_string(),
            "nat".to_string(),
            "-C".to_string(),
            "PREROUTING".to_string(),
            "-m".to_string(),
            "mac".to_string(),
            "--mac-source".to_string(),
            mac.to_string(),
            "-p".to_string(),
            proto.to_string(),
            "--dport".to_string(),
            "53".to_string(),
            "-j".to_string(),
            "REDIRECT".to_string(),
            "--to-ports".to_string(),
            cfg.inbound.dns_port.to_string(),
        ];
        let add_args = vec![
            "-t".to_string(),
            "nat".to_string(),
            "-A".to_string(),
            "PREROUTING".to_string(),
            "-m".to_string(),
            "mac".to_string(),
            "--mac-source".to_string(),
            mac.to_string(),
            "-p".to_string(),
            proto.to_string(),
            "--dport".to_string(),
            "53".to_string(),
            "-j".to_string(),
            "REDIRECT".to_string(),
            "--to-ports".to_string(),
            cfg.inbound.dns_port.to_string(),
        ];
        maybe_add_iptables_rule("iptables", &check_args, &add_args, out)?;
    }
    Ok(())
}

#[cfg(target_os = "linux")]
fn maybe_add_iptables_rule(
    program: &str,
    check_args: &[String],
    add_args: &[String],
    out: &mut EnforcementResult,
) -> Result<()> {
    let exists = Command::new(program)
        .args(check_args)
        .status()
        .with_context(|| format!("failed to check rule: {} {:?}", program, check_args))?
        .success();
    if !exists {
        run(program, add_args)?;
        let mut rollback = add_args.to_vec();
        if let Some(op) = rollback.get_mut(2) {
            *op = "-D".to_string();
        }
        out.rollback_commands
            .push(format!("{} {}", program, rollback.join(" ")));
    }
    Ok(())
}

#[cfg(target_os = "linux")]
fn run(cmd: &str, args: &[String]) -> Result<()> {
    let status = Command::new(cmd)
        .args(args)
        .status()
        .with_context(|| format!("failed to run command: {} {:?}", cmd, args))?;
    if !status.success() {
        anyhow::bail!("command failed: {} {:?}", cmd, args);
    }
    Ok(())
}

fn detect_primary_ipv4() -> Result<String> {
    #[cfg(target_os = "linux")]
    {
        let out = Command::new("sh")
            .arg("-c")
            .arg("ip route get 1.1.1.1 | awk '{for(i=1;i<=NF;i++) if($i==\"src\") {print $(i+1); exit}}'")
            .output()
            .context("failed to run ip route query")?;
        let ip = String::from_utf8_lossy(&out.stdout).trim().to_string();
        if !ip.is_empty() {
            return Ok(ip);
        }
    }

    #[cfg(target_os = "macos")]
    {
        let out = Command::new("sh")
            .arg("-c")
            .arg("route -n get default | awk '/interface:/{print $2}' | xargs -I{} ipconfig getifaddr {}")
            .output()
            .context("failed to query default interface ip")?;
        let ip = String::from_utf8_lossy(&out.stdout).trim().to_string();
        if !ip.is_empty() {
            return Ok(ip);
        }
    }

    anyhow::bail!("unable to detect primary ipv4 address")
}

pub fn write_rollback_script(work_dir: &PathBuf, commands: &[String]) -> Result<PathBuf> {
    let path = work_dir.join("rollback.sh");
    fs::create_dir_all(work_dir)
        .with_context(|| format!("failed to create {}", work_dir.display()))?;
    let mut body = String::from("#!/usr/bin/env sh\nset -e\n");
    for c in commands {
        body.push_str(c);
        body.push('\n');
    }
    fs::write(&path, body).with_context(|| format!("failed to write {}", path.display()))?;
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        let perm = fs::Permissions::from_mode(0o700);
        fs::set_permissions(&path, perm)
            .with_context(|| format!("failed to chmod {}", path.display()))?;
    }
    Ok(path)
}

pub fn execute_rollback(path: &PathBuf) -> Result<()> {
    let status = Command::new("sh")
        .arg(path)
        .status()
        .with_context(|| format!("failed to execute rollback script: {}", path.display()))?;
    if !status.success() {
        anyhow::bail!("rollback failed with status {}", status);
    }
    Ok(())
}
